engines:
 rubocop:
   enabled: false
 duplication:
   enabled: true
 metrics:
   enabled: true
 coverage:
   enabled: false
exclude_paths:
  - lib/ArduinoJson/**
  - lib/PubSubClient/**
  - lib/WiFiManager/**