/* This file is auto-generated by THiNX API and arduino-docker-builder from device's "environment" object. */

// In order of importance and churn:

// 1. Backend Selection
#define ENVIRONMENT_ENV 1 // 1 = staging; 0 = production

#define ENV_HASH "cafebabe" // causes ignoring version to prevent updates on same version in-development